services:
  backend:
    image: ${HUB}/${STACK_NAME}/base-${IMAGE_NAMESPACE}-backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
      cache_from:
        - ${HUB}/${STACK_NAME}/base-${IMAGE_NAMESPACE}-backend:latest

  frontend:
    image: ${HUB}/${STACK_NAME}/base-${IMAGE_NAMESPACE}-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
      cache_from:
        - ${HUB}/${STACK_NAME}/base-${IMAGE_NAMESPACE}-frontend:latest
