version: '3.8'

services:
  backend:
    image: ${HUB}/${STACK_NAME}/${IMAGE_NAMESPACE}-backend:${IMAGE_TAG:-latest}
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 0s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}_api.rule=Host(`api-identity.${DOMAIN}`)"
        - "traefik.http.routers.${STACK_NAME}_api.entrypoints=websecure"
        - "traefik.http.routers.${STACK_NAME}_api.tls.certresolver=cloudflare"
        - "traefik.http.services.${STACK_NAME}_api.loadbalancer.server.port=9501"

  frontend:
    image: ${HUB}/${STACK_NAME}/${IMAGE_NAMESPACE}-frontend:${IMAGE_TAG:-latest}
    networks:
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 0s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME}_web.rule=Host(`identity.${DOMAIN}`)"
        - "traefik.http.routers.${STACK_NAME}_web.entrypoints=websecure"
        - "traefik.http.routers.${STACK_NAME}_web.tls.certresolver=cloudflare"
        - "traefik.http.services.${STACK_NAME}_web.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
